# Generated by Django 3.1.5 on 2021-01-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='メーカー')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='機種')),
                ('release_date', models.DateField(verbose_name='発売日')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_manager.maker', verbose_name='メーカー')),
            ],
        ),
        migrations.CreateModel(
            name='SmartPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.IntegerField(verbose_name='データ容量(GB)')),
                ('color', models.TextField(verbose_name='色')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smartphone', to='stock_manager.product', verbose_name='機種')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.TextField(verbose_name='OSバージョン')),
                ('price', models.IntegerField(verbose_name='販売価格(円)')),
                ('prd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='stock_manager.smartphone', verbose_name='機種')),
            ],
        ),
    ]
